language: objective-c
cache: cocoapods
xcode_workspace: SWTableViewCellFixed.xcworkspace
xcode_scheme: SWTableViewCellFixed
xcode_sdk: iphonesimulator
osx_image: xcode7.1

before_install:
  - gem install cocoapods slather -N

after_success: slather
